id = "zed-openedge-abl"
name = "OpenEdge ABL"
version = "0.0.1"
schema_version = 1
authors = ["Kamil Jakubus <kamil.jakubus@usagi.coffee>"]
description = "OpenEdge ABL support"
repository = "https://github.com/usagi-coffee/zed-openedge-abl"
languages = ["languages/abl"]

[grammars.abl]
repository = "https://github.com/jkbz64/tree-sitter-abl-next.git"
rev = "0e0af180cc2201509e54c23b3c02f3e401865eb1"
